package fr.flastar.magiqolsky.shopitems.shop_categories;

public enum Dyes implements IShopCategory {
    WHITE_DYE("minecraft:white_dye", .05f),
    ORANGE_DYE("minecraft:orange_dye", .05f),
    MAGENTA_DYE("minecraft:magenta_dye", .05f),
    LIGHT_BLUE_DYE("minecraft:light_blue_dye", .05f),
    YELLOW_DYE("minecraft:yellow_dye", .05f),
    LIME_DYE("minecraft:lime_dye", .05f),
    PINK_DYE("minecraft:pink_dye", .05f),
    GRAY_DYE("minecraft:gray_dye", .05f),
    LIGHT_GRAY_DYE("minecraft:light_gray_dye", .05f),
    CYAN_DYE("minecraft:cyan_dye", .05f),
    PURPLE_DYE("minecraft:purple_dye", .05f),
    BLUE_DYE("minecraft:blue_dye", .05f),
    RED_DYE("minecraft:red_dye", .05f),
    BROWN_DYE("minecraft:brown_dye", .05f),
    GREEN_DYE("minecraft:green_dye", .05f),
    BLACK_DYE("minecraft:black_dye", .05f),
    WHITE_WOOL("minecraft:white_wool", .1f),
    ORANGE_WOOL("minecraft:orange_wool", .1f),
    MAGENTA_WOOL("minecraft:magenta_wool", .1f),
    LIGHT_BLUE_WOOL("minecraft:light_blue_wool", .1f),
    YELLOW_WOOL("minecraft:yellow_wool", .1f),
    LIME_WOOL("minecraft:lime_wool", .1f),
    PINK_WOOL("minecraft:pink_wool", .1f),
    GRAY_WOOL("minecraft:gray_wool", .1f),
    LIGHT_GRAY_WOOL("minecraft:light_gray_wool", .1f),
    CYAN_WOOL("minecraft:cyan_wool", .1f),
    PURPLE_WOOL("minecraft:purple_wool", .1f),
    BLUE_WOOL("minecraft:blue_wool", .1f),
    RED_WOOL("minecraft:red_wool", .1f),
    BROWN_WOOL("minecraft:brown_wool", .1f),
    GREEN_WOOL("minecraft:green_wool", .1f),
    BLACK_WOOL("minecraft:black_wool", .1f),
    WHITE_CONCRETE("minecraft:white_concrete", 2.f),
    ORANGE_CONCRETE("minecraft:orange_concrete", 2.f),
    MAGENTA_CONCRETE("minecraft:magenta_concrete", 2.f),
    LIGHT_BLUE_CONCRETE("minecraft:light_blue_concrete", 2.f),
    YELLOW_CONCRETE("minecraft:yellow_concrete", 2.f),
    LIME_CONCRETE("minecraft:lime_concrete", 2.f),
    PINK_CONCRETE("minecraft:pink_concrete", 2.f),
    GRAY_CONCRETE("minecraft:gray_concrete", 2.f),
    LIGHT_GRAY_CONCRETE("minecraft:light_gray_concrete", 2.f),
    CYAN_CONCRETE("minecraft:cyan_concrete", 2.f),
    PURPLE_CONCRETE("minecraft:purple_concrete", 2.f),
    BLUE_CONCRETE("minecraft:blue_concrete", 2.f),
    RED_CONCRETE("minecraft:red_concrete", 2.f),
    BROWN_CONCRETE("minecraft:brown_concrete", 2.f),
    GREEN_CONCRETE("minecraft:green_concrete", 2.f),
    BLACK_CONCRETE("minecraft:black_concrete", 2.f),
    WHITE_CONCRETE_POWDER("minecraft:white_concrete_powder", 2.f),
    ORANGE_CONCRETE_POWDER("minecraft:orange_concrete_powder", 2.f),
    MAGENTA_CONCRETE_POWDER("minecraft:magenta_concrete_powder", 2.f),
    LIGHT_BLUE_CONCRETE_POWDER("minecraft:light_blue_concrete_powder", 2.f),
    YELLOW_CONCRETE_POWDER("minecraft:yellow_concrete_powder", 2.f),
    LIME_CONCRETE_POWDER("minecraft:lime_concrete_powder", 2.f),
    PINK_CONCRETE_POWDER("minecraft:pink_concrete_powder", 2.f),
    GRAY_CONCRETE_POWDER("minecraft:gray_concrete_powder", 2.f),
    LIGHT_GRAY_CONCRETE_POWDER("minecraft:light_gray_concrete_powder", 2.f),
    CYAN_CONCRETE_POWDER("minecraft:cyan_concrete_powder", 2.f),
    PURPLE_CONCRETE_POWDER("minecraft:purple_concrete_powder", 2.f),
    BLUE_CONCRETE_POWDER("minecraft:blue_concrete_powder", 2.f),
    RED_CONCRETE_POWDER("minecraft:red_concrete_powder", 2.f),
    BROWN_CONCRETE_POWDER("minecraft:brown_concrete_powder", 2.f),
    GREEN_CONCRETE_POWDER("minecraft:green_concrete_powder", 2.f),
    BLACK_CONCRETE_POWDER("minecraft:black_concrete_powder", 2.f),
    WHITE_TERRACOTTA("minecraft:white_terracotta", 2.f),
    ORANGE_TERRACOTTA("minecraft:orange_terracotta", 2.f),
    MAGENTA_TERRACOTTA("minecraft:magenta_terracotta", 2.f),
    LIGHT_BLUE_TERRACOTTA("minecraft:light_blue_terracotta", 2.f),
    YELLOW_TERRACOTTA("minecraft:yellow_terracotta", 2.f),
    LIME_TERRACOTTA("minecraft:lime_terracotta", 2.f),
    PINK_TERRACOTTA("minecraft:pink_terracotta", 2.f),
    GRAY_TERRACOTTA("minecraft:gray_terracotta", 2.f),
    LIGHT_GRAY_TERRACOTTA("minecraft:light_gray_terracotta", 2.f),
    CYAN_TERRACOTTA("minecraft:cyan_terracotta", 2.f),
    PURPLE_TERRACOTTA("minecraft:purple_terracotta", 2.f),
    BLUE_TERRACOTTA("minecraft:blue_terracotta", 2.f),
    RED_TERRACOTTA("minecraft:red_terracotta", 2.f),
    BROWN_TERRACOTTA("minecraft:brown_terracotta", 2.f),
    GREEN_TERRACOTTA("minecraft:green_terracotta", 2.f),
    BLACK_TERRACOTTA("minecraft:black_terracotta", 2.f),
    WHITE_STAINED_GLASS("minecraft:white_stained_glass", 2.f),
    ORANGE_STAINED_GLASS("minecraft:orange_stained_glass", 2.f),
    MAGENTA_STAINED_GLASS("minecraft:magenta_stained_glass", 2.f),
    LIGHT_BLUE_STAINED_GLASS("minecraft:light_blue_stained_glass", 2.f),
    YELLOW_STAINED_GLASS("minecraft:yellow_stained_glass", 2.f),
    LIME_STAINED_GLASS("minecraft:lime_stained_glass", 2.f),
    PINK_STAINED_GLASS("minecraft:pink_stained_glass", 2.f),
    GRAY_STAINED_GLASS("minecraft:gray_stained_glass", 2.f),
    LIGHT_GRAY_STAINED_GLASS("minecraft:light_gray_stained_glass", 2.f),
    CYAN_STAINED_GLASS("minecraft:cyan_stained_glass", 2.f),
    PURPLE_STAINED_GLASS("minecraft:purple_stained_glass", 2.f),
    BLUE_STAINED_GLASS("minecraft:blue_stained_glass", 2.f),
    RED_STAINED_GLASS("minecraft:red_stained_glass", 2.f),
    BROWN_STAINED_GLASS("minecraft:brown_stained_glass", 2.f),
    GREEN_STAINED_GLASS("minecraft:green_stained_glass", 2.f),
    BLACK_STAINED_GLASS("minecraft:black_stained_glass", 2.f),
    GLASS("minecraft:glass", 2.f),
    TINTED_GLASS("minecraft:tinted_glass", 2.f),
    WHITE_CANDLE("minecraft:white_candle", 2.f),
    ORANGE_CANDLE("minecraft:orange_candle", 2.f),
    MAGENTA_CANDLE("minecraft:magenta_candle", 2.f),
    LIGHT_BLUE_CANDLE("minecraft:light_blue_candle", 2.f),
    YELLOW_CANDLE("minecraft:yellow_candle", 2.f),
    LIME_CANDLE("minecraft:lime_candle", 2.f),
    PINK_CANDLE("minecraft:pink_candle", 2.f),
    GRAY_CANDLE("minecraft:gray_candle", 2.f),
    LIGHT_GRAY_CANDLE("minecraft:light_gray_candle", 2.f),
    CYAN_CANDLE("minecraft:cyan_candle", 2.f),
    PURPLE_CANDLE("minecraft:purple_candle", 2.f),
    BLUE_CANDLE("minecraft:blue_candle", 2.f),
    RED_CANDLE("minecraft:red_candle", 2.f),
    BROWN_CANDLE("minecraft:brown_candle", 2.f),
    GREEN_CANDLE("minecraft:green_candle", 2.f),
    BLACK_CANDLE("minecraft:black_candle", 2.f);

    private final String id;
    private final float price;

    Dyes(String id, float price) {
        this.id = id;
        this.price = price;
    }

    @Override
    public String getID() {
        return id;
    }

    @Override
    public float getPrice() {
        return price;
    }
}
