package fr.flastar.magiqolsky.shopitems.shop_categories;

public enum Fisherman implements IShopCategory {
    RAW_COD("minecraft:cod", 75.f),
    RAW_SALMON("minecraft:salmon", 75.f),
    TROPICAL_FISH("minecraft:tropical_fish", 75.f),
    PUFFERFISH("minecraft:pufferfish", 75.f),
    ANCHOVY("nexo:anchovy", 187.5f),
    BLUEGILL("nexo:bluegill", 187.5f),
    CRUCIAN_CARP("nexo:crucian_carp", 187.5f),
    CUTLASS_FISH("nexo:cutlass_fish", 187.5f),
    EEL("nexo:eel", 187.5f),
    GOLD_FISH("nexo:gold_fish", 187.5f),
    HORSESHOE_CRAB("nexo:horseshoe_crab", 187.5f),
    MANDARIN_FISH("nexo:mandarin_fish", 187.5f),
    MINNOW("nexo:minnow", 187.5f),
    MUD_FISH("nexo:mud_fish", 187.5f),
    PENIS_FISH("nexo:penis_fish", 187.5f),
    SEA_ANEMONE("nexo:sea_anemone", 187.5f),
    SEA_CUCUMBER("nexo:sea_cucumber", 187.5f),
    AZURE_MIRAGE("nexo:azure_mirage", 187.5f),
    CELESTIAL_SERPENT("nexo:celestial_serpent", 187.5f),
    CINDERGLOW_WISP("nexo:cinderglow_wisp", 187.5f),
    COSMIC_SERPENT("nexo:cosmic_serpent", 187.5f),
    CRIMSON_GLINT("nexo:crimson_glint", 187.5f),
    CRIMSON_WHISPER("nexo:crimson_whisper", 187.5f),
    DREADED_RIPTIDE("nexo:dreaded_riptide", 187.5f),
    DREADLIGHT_SHADOW("nexo:dreadlight_shadow", 187.5f),
    EMBERSTONE_GLINT("nexo:emberstone_glint", 187.5f),
    HORIZON_SHIMMER("nexo:horizon_shimmer", 187.5f),
    LUMINOUS_VORTEX("nexo:luminous_vortex", 187.5f),
    MYSTIC_ELIPSOR("nexo:mystic_elipsor", 187.5f),
    OBLIVION_WISP("nexo:oblivion_wisp", 187.5f),
    PENUMBRAL_WHIRL("nexo:penumbral_whirl", 187.5f),
    RADIANT_GALE("nexo:radiant_gale", 187.5f),
    RAINSONG_ECHO("nexo:rainsong_echo", 187.5f),
    SABLE_SHROUD("nexo:sable_shroud", 187.5f),
    SERPENTS_WHISPER("nexo:serpents_whisper", 187.5f),
    SHIMMERING_ABYSS("nexo:shimmering_abyss", 187.5f),
    SILTSHADE_WRAITH("nexo:siltshade_wraith", 187.5f),
    SOLARIS_FLICKER("nexo:solaris_flicker", 187.5f),
    STARLIGHT_MIRAGE("nexo:starlight_mirage", 187.5f),
    STELLAR_DRIFTWODD("nexo:stellar_driftwood", 187.5f),
    BLUE_TANG("nexo:blue_tang", 375.f),
    BUTTERFLY_FISH("nexo:butterfly_fish", 375.f),
    CROTCH("nexo:crotch", 375.f),
    CYAN_JELLYFISH("nexo:cyan_jellyfish", 375.f),
    FLYING_FISH("nexo:flying_fish", 375.f),
    PINK_HIPPOCAMPUS("nexo:pink_hippocampus", 375.f),
    RIBBON_EEL("nexo:ribbon_eel", 375.f),
    SEA_SQUIRT("nexo:sea_squirt", 375.f),
    STAR_FISH("nexo:star_fish", 375.f),
    MARROWVEIL_BRINEFISH("nexo:marrowveil_brinefish", 375.f),
    ETHERWAVE_ENVOY("nexo:etherwave_envoy", 375.f),
    ABYSSAL_SPECTER("nexo:abyssal_specter", 375.f),
    AETHERIC_SPINNER("nexo:aetheric_spinner", 375.f),
    CRIMSON_CURRENTS("nexo:crimson_currents", 375.f),
    CRIMSON_TSUNAMI("nexo:crimson_tsunami", 375.f),
    DUSKVEIL_SPECTER("nexo:duskveil_specter", 375.f),
    FROSTFIRE_FLICKER("nexo:frostfire_flicker", 375.f),
    HORIZON_DANCER("nexo:horizon_dancer", 375.f),
    PHANTOM_TIDEBRINGER("nexo:phantom_tidebringer", 375.f),
    QUICKSILVER_MIRAGE("nexo:quicksilver_mirage", 375.f),
    RADIANT_PEARLFISH("nexo:radiant_pearlfish", 375.f),
    SUNDROP_LANTERNFISH("nexo:sundrop_lanternfish", 375.f),
    VORTEX_ECHO("nexo:vortex_echo", 375.f),
    VORTEX_SHADE("nexo:vortex_shade", 375.f),
    ZEPHYR_GLIDER("nexo:zephyr_glider", 375.f),
    WHISPWHIRL_DANCER("nexo:whispwhirl_dancer", 375.f),
    ZANCLUS_CORNUTUS("nexo:zanclus_cornutus", 750.f),
    CLIONE("nexo:clione", 750.f),
    CORAL_HIPPOCAMPUS("nexo:coral_hippocampus", 750.f),
    OAR_FISH("nexo:oar_fish", 750.f),
    TRUMPET_FISH("nexo:trumpet_fish", 750.f),
    NEBULA_SLUMBERER("nexo:nebula_slumberer", 750.f),
    CELESTIAL_DUNE("nexo:celestial_dune", 750.f),
    ECHOING_PHANTOM("nexo:echoing_phantom", 750.f),
    GLEAMING_PHANTASM("nexo:gleaming_phantasm", 750.f),
    GLOOMSHADE_RECLUSE("nexo:gloomshade_recluse", 750.f),
    PHANTOM_MIRAGE("nexo:phantom_mirage", 750.f),
    STORMREAVER_TEMPEST("nexo:stormreaver_tempest", 750.f),
    TWILIGHT_PRISM("nexo:twilight_prism", 750.f),
    WHISPERCURRENT_MISTFISH("nexo:whispercurrent_mistfish", 750.f),
    GOLD_HIPPOCAMPUS("nexo:gold_hippocampus", 1500.f),
    CELESTIAL_HARBINGER("nexo:celestial_harbinger", 1500.f),
    TWILIGHT_GLOWTAIL("nexo:twilight_glowtail", 1500.f),
    HOLLOW_ECHO("nexo:hollow_echo", 1500.f),
    NEBULAFLARE_SPECTRA("nexo:nebulaflare_spectra", 1500.f),
    SHARDFLARE_PHANTOM("nexo:shardflare_phantom", 1500.f),
    TEMPESTS_BANE("nexo:tempests_bane", 1500.f),
    TIDAL_SPECTRE("nexo:tidal_spectre", 1500.f),
    WHIRLPOOL_WRAITH("nexo:whirlpool_wraith", 1500.f),
    OBSIDIAN_MIRAGE("nexo:obsidian_mirage", 1500.f),
    FLAMEWROUGHT_RAY("nexo:flamewrought_ray", 1500.f),
    BIGGOLD_FISH("nexo:biggold_fish", 1500.f),
    RIFTWALKER("nexo:riftwalker", 3000.f),
    CRYSTALLINE_LURKER("nexo:crystalline_lurker", 3000.f),
    INFERNO_GLINT("nexo:inferno_glint", 3000.f),
    MOONSHADOW_GLIDER("nexo:moonshadow_glider", 3000.f),
    STARSHINE_SLIDER("nexo:starshine_slider", 3000.f),
    GOLDEN_FISH("nexo:golden_fish", 3000.f);

    private final String id;
    private final float price;

    Fisherman(String id, float price) {
        this.id = id;
        this.price = price;
    }

    @Override
    public String getID() {
        return id;
    }

    @Override
    public float getPrice() {
        return price;
    }
}
